#!/usr/bin/env perl

use utf8;
use v5.36;
use strict;
use warnings;

use FindBin qw/$Bin/;
use File::Spec::Functions qw/:DEFAULT rel2abs/;
use Getopt::Long qw/:config require_order/;
use Pod::Usage;

my %opt = (lines => 0);
GetOptions(\%opt, 'help', 'n=i' => \$opt{lines}) or pod2usage(2);

pod2usage(-exitval => 0, -verbose => 2) if ($opt{help});
pod2usage(2) unless (@ARGV);

my $root = rel2abs(catfile($Bin, '..'));
my $index_dir = catfile($root, 'search');

my @cmd = ('zoekt', '-r', '-index_dir', $index_dir, '--', @ARGV);

my $pid = open(my $fh, '-|') // die "fork failed: $!";
if ($pid == 0) {
  open(STDERR, '>&', \*STDOUT) or die "dup STDERR: $!";
  exec {$cmd[0]} @cmd or die "exec zoekt: $!";
}

my $n = 0;
while (my $line = <$fh>) {
  print $line;
  last if ($opt{lines} > 0 && ++$n >= $opt{lines});
}
close($fh);
exit($? >> 8);

__END__

=head1 NAME

zcs - zoekt code search wrapper

=head1 SYNOPSIS

  zcs [-n LINES] <query>
  zcs -- -file:test foo    # use -- before queries that start with '-'

=head1 OPTIONS

=over

=item B<-n> LINES

Truncate output to the first LINES lines.

=item B<--help>

Show this help.

=back

=cut
